# Generated by Django 4.1.2 on 2023-05-02 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_possibleadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='title',
            new_name='Village',
        ),
    ]
